### ISSUE TITLE
Add pp to similar tools

### ISSUE THREAD

**Issue by rojenzaman** [TekWizely/bash-tpl#15]
You can add Adrian's tool [pp](https://adi.onl/pp.html) to similar tools section.

description of *pp*:

> ## pp
> a preprocessor
>
> pp allows embedding sh code in files of any type by nesting it inside the #!\n token, where \n is a new line. That means that if you'd like a simple loop or an if inside an HTML file for instance, you could use pp.
> 
> https://adi.onl/pp.html

**Comment by TekWizely** [comment]
[Done](https://github.com/TekWizely/bash-tpl/commit/6bc057cf9df74b1d6ef673616b517be01d245fc5),  thanks for the note !
