### ISSUE TITLE
Allow variable with `.tpl` file path as argument to `.INCLUDE` directive

### ISSUE THREAD

**Issue by benjamindblock** [TekWizely/bash-tpl#16]
First, thanks for the great work on `bash-tpl` -- I've been using it to great effect when making some new static sites.

I ran across an issue recently -- it appears that `.INCLUDE` cannot be used with a variable to render another `.tpl` file dynamically (eg., `.INCLUDE $1`).

Bash version:
`GNU bash, version 3.2.57(1)-release (arm64-apple-darwin22)`

Repro steps:
1. Create a top-level "layout" file.
```bash
printf '<div class="container">\n  .INCLUDE $1\n</div>\n' > layout.tpl
```
Which produces: 
```html
<div class="container">
  .INCLUDE $1
</div>
```

2. Create a "partial" view file with some content
```bash
echo '<span>Subcontent should be displayed</span>' > partial.tpl
```
Which produces:
```html
<span>Subcontent should be displayed</span>
```

3. Call `bash-tpl`
```
bash-tpl layout.tpl partial.tpl
```

This produces the following:
```bash
printf "%s\n" \<div\ class=\"container\"\>
  printf "%s\n" \ \ \</div\>
```

I expected this output:
```bash
printf "%s\n" \<div\ class=\"container\"\>
  printf "%s\n" \ \ Subcontent\ should\ be\ displayed
printf "%s\n" \</div\>
```

I would expect that the argument `$1` could be used in the `.INCLUDE` directive to dynamically pass in the `.tpl` file that should be rendered. I also could be missing something straightforward here, in which case any insight would be appreciated.

If this is not currently a feature, having this ability in `bash-tpl` would be great.

**Comment by TekWizely** [comment]
Greetings @benjamindblock and thank you for using my project and for taking the time to open this issue !

I've done some tests and I am pleasantly surprised !! it looks like the technique I use to parse directive arguments _does_ honor variable references.

The issue you're seeing in your example is that the `$[0-9]` variables no-longer reference the original command line args but are instead referencing the arguments passed to the `process_directive` function that handles the directive.

If you wanna see something cool, try this:

_layout.tpl_
```
<div class="container">
  .INCLUDE ${INCLUDE_TPL}
</div>
```

_partial.tpl_
```
<span>Subcontent should be displayed</span>
```

_process template_
```
$ INCLUDE_TPL=partial.tpl bash-tpl layout.tpl
```

_output_
```
printf "%s\n" \<div\ class=\"container\"\>
  printf "%s\n" \ \ \<span\>Subcontent\ should\ be\ displayed\</span\>
printf "%s\n" \</div\>
```

To officially support abusing this technique within bash_tpl, I think we need to expose the command line arguments in a variable that can be referenced from the directive.

maybe something like `$ARGS[x]`

Honestly though that feels a bit messy in the case of multiple arguments being available for use.

Maybe adding a command-line flag to create named variables could more useful.  Something like:

```
$ bash-tpl layout.tpl --var INCLUDE_TPL=partial.tpl
```

Or maybe a `.ENV` directive that could read a `.env` file  ..

I'll grind on this a bit more, but in the meantime lemme know your thoughts and thanks again for participating in my project!

-TW

**Comment by benjamindblock** [comment]
@TekWizely Aha -- thanks for the details on the `process_directive` function -- I tried out the `.INCLUDE` call with the explicit named variable and everything worked as expected. Brilliant.

I really like the idea of a `.ENV` directive that could load variables from an `.env` type of file. I'm actually doing a similar hack with `eval(...)` right now to accomplish just that type of behavior. Brief explanation following...

In my static site generator, each page has a `.meta` file that can include a `tpl=` key if multiple pages share a template (like blog posts).

```bash
# blog20230415.meta
title="Website | April 15th"
content="Long text..."
tpl="tpls/blog_template.tpl.html
```

I then use `eval(...)` to load those variables and render the primary site layout _and_ the subcontent for a particular page with those vars present.
```bash
content() {
  bash <(bin/bash-tpl tpls/layout.tpl.html)
}

renderPage() {
  echo "$(eval $(cat "$1") content)"
}

# Example: renderPage "renderPage "blog20230415.meta" > "blog20230415.html"
```

Example view files:
```html
<!-- tpls/layout.tpl.html -->
<header><% ${title} %></header>
<body>
  .INCLUDE ${tpl}
</body>
```

```html
<!-- tpls/blog_template.tpl.html -->
<div><% ${content} %></div>
```

If an `.ENV` directive was included, we could simplify this nicely.
```bash
renderPage() {
  echo "$(bash <(bin/bash-tpl tpls/layout.tpl.html blog20230415.meta))"
}
```
```html
<!-- tpls/layout.tpl.html -->
%
  .ENV ${1}
%
<header><% ${title} %></header>
<body>
  .INCLUDE ${tpl}
</body>
```

**Comment by benjamindblock** [comment]
I've come up with a workaround for rendering subcontent that avoids `.INCLUDE` and instead just calls `source` on the subcontent and renders it in place with the standard `<% %>` tags. It's been working pretty nicely, though I've still been using `.INCLUDE` though for partials that require no args (as it has a nicer interface for this sort of thing).

Here's a small example:

```bash
renderContent() {
  META_FILE="$1"
  bash <(bin/bash-tpl tpls/site/layout.tpl.html) "${META_FILE}"
}
```

`blogs/1/index.meta`
```
title="Blog Post #1"
tpl="blog.tpl.html"
content="Some content"
```

`layout.html.tpl`
```html
%
  META_FILE="$1"
  source "${META_FILE}"

  # Fail if no "$tpl" is not present.
  SUBCONTENT="$(source <(bin/bash-tpl ${tpl:?}))"
%
<head>
  <title><% $title %></title>
</head>

<div id="subcontent">
  <% ${SUBCONTENT} %>
</div>
```

`blog.tpl.html`
```
<div id="blog">
  <% "${content:?}" %>
</div>
```

This would all get kicked off in a script running: `renderContent "blogs/1/index.meta"`

**Comment by TekWizely** [comment]
hey @benjamindblock just a quick ping to see if you had a chance to read my post above?

**Comment by benjamindblock** [comment]
Hey @TekWizely -- yes, thanks for all the details! I was, like you suspected, calling bash-tpl many more times than necessary.

With your updates I was able to get the build times for my static site from **11s** down to **3s** (the site has ~40 HTML pages to build). There may still be a few more optimizations I can make to speed that up a little bit more.

I'll be AFK for a few days but will post some more details about my improvements after that!

**Comment by TekWizely** [comment]
Hey @benjamindblock just checking back to see how things are going?
BTW: I think I may have stumbled onto your site?
* https://eveningjazz.net/about.html

**Comment by benjamindblock** [comment]
Hey @TekWizely, apologies for the late response -- busy summer. Did some work on the site this week and made the repo public (for now), in case you're interested in taking a look at the patterns I setup with Bash-TPL (thanks to your input): https://github.com/benjamindblock/eveningjazz.net

Ultimately I was able to get the full site build down to ~3s for 33 `.html` pages. Not too bad, I think!

**Comment by TekWizely** [comment]
@benjamindblock  Thanks for the final update post - I'm going to close this now as I think we got a working solution to the initial concern.  Thanks!
