### ISSUE TITLE
bash-tpl is in my bash compiler

### ISSUE THREAD

**Issue by fchastanet** [TekWizely/bash-tpl#20]
Hello,

I'm using your project inside mine.
It is a kind of bash compiler (it aggregates several files together in order to generate a unique bash file).

bash-tpl is in the heart of this compiler, so this message is just to say thank you for your work.

I added a reference to your project here 
https://github.com/fchastanet/bash-tools-framework#4-acknowledgements

kind regards,
François Chastanet

**Comment by TekWizely** [comment]
Hi @fchastanet ! Thanks for the note, and for the callout on you project page.
Your project appears to be quite comprehensive - I wish you luck on your project and hope the community enjoys your extensive framework !

**Comment by TekWizely** [comment]
Just cleaning up and closing some older issues - Hope your project is doing well and thanks again for the callout on your project page !
